# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/ycw/Group_18_final_project/Group_18_final_project.cache/wt [current_project]
set_property parent.project_path C:/Users/ycw/Group_18_final_project/Group_18_final_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/ycw/Desktop/KeyboardSampleCode/KeyboardSampleCode/KeyboardSampleCode/ip [current_project]
set_property ip_output_repo c:/Users/ycw/Group_18_final_project/Group_18_final_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/ycw/Group_18_final_project/Group_18_final_project.srcs/sources_1/new/Bell.v
  C:/Users/ycw/Group_18_final_project/Group_18_final_project.srcs/sources_1/new/CreateLargePulse.v
  C:/Users/ycw/Group_18_final_project/Group_18_final_project.srcs/sources_1/new/DownCounter.v
  C:/Users/ycw/Group_18_final_project/Group_18_final_project.srcs/sources_1/imports/Desktop/KeyboardDecoder.v
  C:/Users/ycw/Group_18_final_project/Group_18_final_project.srcs/sources_1/new/LED7SEG.v
  C:/Users/ycw/Group_18_final_project/Group_18_final_project.srcs/sources_1/new/Music.v
  C:/Users/ycw/Group_18_final_project/Group_18_final_project.srcs/sources_1/new/OnePulse.v
  C:/Users/ycw/Group_18_final_project/Group_18_final_project.srcs/sources_1/imports/Desktop/PWM.v
  C:/Users/ycw/Group_18_final_project/Group_18_final_project.srcs/sources_1/imports/Desktop/PlayerCtrl.v
  C:/Users/ycw/Group_18_final_project/Group_18_final_project.srcs/sources_1/new/SampleDisplay.v
  C:/Users/ycw/Group_18_final_project/Group_18_final_project.srcs/sources_1/new/StopWatch.v
  C:/Users/ycw/Group_18_final_project/Group_18_final_project.srcs/sources_1/new/alarm.v
  C:/Users/ycw/Group_18_final_project/Group_18_final_project.srcs/sources_1/new/clock_divider.v
  C:/Users/ycw/Group_18_final_project/Group_18_final_project.srcs/sources_1/new/Top.v
}
read_ip -quiet c:/Users/ycw/Group_18_final_project/Group_18_final_project.srcs/sources_1/ip/KeyboardCtrl_0/KeyboardCtrl_0.xci
set_property is_locked true [get_files c:/Users/ycw/Group_18_final_project/Group_18_final_project.srcs/sources_1/ip/KeyboardCtrl_0/KeyboardCtrl_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ycw/Group_18_final_project/Group_18_final_project.srcs/constrs_1/imports/Desktop/Basys3_Constraints.xdc
set_property used_in_implementation false [get_files C:/Users/ycw/Group_18_final_project/Group_18_final_project.srcs/constrs_1/imports/Desktop/Basys3_Constraints.xdc]


synth_design -top Top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Top.dcp

catch { report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb }
